<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SPTarkov.Common" Version="4.0.0-pre.20251007.1604" />
    <PackageReference Include="SPTarkov.DI" Version="4.0.0-pre.20251007.1604" />
    <PackageReference Include="SPTarkov.Server.Core" Version="4.0.0-pre.20251007.1604" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="WTT-ServerCommonLib">
      <HintPath>..\..\WTT-ServerCommonLib\WTT-ServerCommonLib.dll</HintPath>
    </Reference>
    <Reference Include="WTTServerCommonLib">
      <HintPath>..\..\WTT-ServerCommonLib\WTTServerCommonLib.dll</HintPath>
    </Reference>
  </ItemGroup>

  <!-- This runs post build to copy the contents of the resource folder to a build directory -->
  <Target Name="CopyResources" AfterTargets="PostBuildEvent">
    <ItemGroup>
      <Resources Include="$(ProjectDir)Resources\**\*.*" />
    </ItemGroup>

    <!-- Copy task to copy the resources folder to the bin directory -->
    <Copy
            SourceFiles="@(Resources);"
            DestinationFolder="$(ProjectDir)$(OutDir)%(RecursiveDir)"
    />
  </Target>

</Project>
